import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DesignContextProvider } from "../contexts/design.context";
import Header from "@/components/header/header";
import { AuthContextProvider } from "@/contexts/auth.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextModCalc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </head>
      <body className={`${inter.className}`}>
        <DesignContextProvider>
          <AuthContextProvider>
            <div className="min-h-screen flex flex-wrap flex-col">
              <Header></Header>
              {children}
            </div>
          </AuthContextProvider>
        </DesignContextProvider>
      </body>
    </html>
  );
}
