import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers';
import Header from '@/components/header/header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NextModCalc',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers>
          <div className='min-h-screen flex flex-wrap flex-col'>
            <Header></Header>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
